services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 47Ayan96  # Use a secure password
      POSTGRES_DB: payments_app_db_dev
    ports:
      - "5432:5432"

  payment-system:
    build: .
    ports:
      - "8081:8081"  # Map the development port
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/payments_app_db_dev
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=47Ayan96
      - QUARKUS_PROFILE=dev  # Run with the development profile
    depends_on:
      - postgres