quarkus:
  application:
    name: payment-system
  http:
    port: 8085   # Change from default 8080 to 8081

  profile: dev

  # Database configuration
  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:47Ayan96}
    jdbc:
      url: ${DB_URL:jdbc:postgresql://localhost:5432/payment_db}

  # Debug and Development
  live-reload:
    enabled: true
  debug:
    enabled: true
    port: 5005

  # Logging
  log:
    category:
      "org.lidionbank.paymentsystem":
        level: DEBUG
      "io.quarkus":
        level: INFO

  # Disable dev services
  devservices:
    enabled: false

  # Health check
  smallrye-health:
    ui:
      enable: true

#  # Hibernate configuration
#  hibernate-orm:
#    database:
#      generation: validate
#    log:
#      sql: true
#      format-sql: true
#
#  # Flyway configuration
#  flyway:
#    migrate-at-start: true
#    baseline-on-migrate: true
#    locations: db/migration


  hibernate-orm:
    database:
      generation: validate
    log:
      sql: true

  # Disable Flyway since we created table manually
  flyway:
    enabled: false

# Payment configuration
payment:
  providers:
    stripe:
      enabled: true
      api-key: ${STRIPE_API_KEY}
    bkash:
      enabled: false
    nagad:
      enabled: false


# Messaging configuration (commented out for initial setup)
# mp:
#   messaging:
#     connector:
#       smallrye-amqp:
#         host: localhost
#         port: 5672
#         username: guest
#         password: guest
