# Development profile configuration
quarkus:
  profile: dev
  live-reload:
    enabled: true
  debug:
    enabled: true
    port: 5005
  log:
    category:
      "org.lidionbank.paymentsystem":
        level: DEBUG
  
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/payment_db

amqp:
  host: localhost
  port: 5672
  username: guest
  password: guest


